config/routes.rb
EdifyDonor::Application.routes.draw do

  resources :categories, :except => [:index, :show]
#   resources :forums, :except => :index do
#     resources :topics, :shallow => true, :except => :index do
#       resources :posts, :shallow => true, :except => [:index, :show]
#     end
#     root to: 'categories#index', via: :get
#   end

  authenticated :user do
#     root :to => 'home#dashboard'
    get 'home/list_schools', to: 'home#list_schools'
    get 'schools', to: 'home#list_schools'
    get 'home/show_schools', to: 'home#show_school'
    get 'home/show_schools/:id', to: 'home#show_school'
    get 'school/:id', to: 'home#show_school'
    get 'home/map_schools', to: 'home#map_schools'
    get 'map', to: 'home#map_schools'
    get 'home/dashboard', to: 'home#dashboard'
    get 'home/prayer_list', to: 'home#prayer_list'
    get 'home/prayer_feed', to: 'home#prayer_feed'
    get 'home/school_prayer', to: 'home#school_prayer'
    get 'home/school_visited', to: 'home#school_visited'
    get 'home/want_to_visit_school', to: 'home#want_to_visit_school'
    get 'home/school_visit_tour', to: 'home#school_visit_tour'
    get 'home/virtual_trip', to: 'home#virtual_trip'
    get 'home/tour', to: 'home#tour'
    get 'home/create_prayer_request', to: 'home#create_prayer_request'
    get 'home/pray_for_user/:id', to: 'home#pray_for_user'
    get 'home/create_school_note', to: 'home#create_school_note'
    get 'home/impact_portfolio', to: 'home#impact_portfolio'
    get 'home/schools_visited', to: 'home#schools_visited'
    get 'home/recently_added', to: 'home#recently_added'
    get 'home/tour_toggle', to: 'home#tour_toggle'
    get 'home/my_fundraisers', to: 'home#my_fundraisers'

    # get 'fundraisers/new', to: 'fundraisers#new'
    # get 'fundraisers/edit', to: 'fundraisers#edit'


    get 'home/school_info_window/:id', to: 'home#school_info_window'

#     if Rails.env.production?
# #       scope :protocol => 'http://', :constraints => { :protocol => 'http://', :domain => "edify-donor.herokuapp.com" } do
# #         resources :donations, :constraints => { :protocol => 'http://', :domain => "edify-donor.herokuapp.com" }
# #       end
#       get 'donations/new', to: redirect("http://edify-donor.herokuapp.com/donations/new"), :constraints => { :protocol => "http://" }
#     end
    get 'donations/fundraiser', to: 'donations#fundraiser'
    get 'donations/create_fundraiser_donation', to: 'donations#create_fundraiser_donation'

    resources :donations
    get 'fundraisers/list', to: 'fundraisers#list'

    resources :fundraisers
  end
  
  get 'iframe_map', to: 'home#iframe_map'
  get 'iframe_school_info_window/:id', to: 'home#iframe_school_info_window'
  
  get 'fundraisers/list', to: 'fundraisers#list'
  get 'fundraisers', to: 'fundraisers#index'
  get 'fundraisers/:id', to: 'fundraisers#show'
  get 'donations/fundraiser', to: 'donations#fundraiser'
  get 'donations/create_fundraiser_donation', to: 'donations#create_fundraiser_donation'

  root :to => "home#index"
  devise_for :users
  resources :users


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  include ApplicationHelper
  include HomeHelper

  require 'pp'
  require 'uri'
  require 'open-uri'
  require 'openssl'
  require 'json'
  require 's3'

  def index
    if Rails.env.development?
      @newest_four = JSON.parse(open("http://localhost:5000/api/home_data/newest_four?token=784c7d6a5e6af6f24cba13e636ae506e").read)
      pp @newest_four
    else
      @newest_four = SchoolDbNewestFour.cached_request
    end
    render layout: "index"
  end

  def dashboard
    if Rails.env.development?
      @newest_four = JSON.parse(open("http://localhost:5000/api/home_data/newest_four?token=784c7d6a5e6af6f24cba13e636ae506e").read)
    else
      @newest_four = SchoolDbNewestFour.cached_request
    end
    @recent_prayer_for_donor = UserAction.where(:to_user_id => current_user.id).where("created_at > ?", 6.weeks.ago).last
  end

  def prayer_list
    @prayer_list = current_user.school_prayers.all
  end

  def prayer_feed
    @prayer_list = SchoolPrayer.all
  end

  def virtual_trip
    @school_wishlist = current_user.want_to_visit_schools.all.group_by(&:country)
    pp @school_wishlist
  end

  def impact_portfolio
    @donations = Donation.where(user_id: current_user.id)
  end

  def schools_visited
    @schools_visited = current_user.school_visits.all
  end

  def recently_added
    if Rails.env.development?
      @newest_four = JSON.parse(open("http://localhost:5000/api/home_data/newest_four?token=784c7d6a5e6af6f24cba13e636ae506e").read)
    else
      @newest_four = SchoolDbNewestFour.cached_request
    end
  end

  def my_fundraisers
    @fundraisers = Fundraiser.where(user_id: current_user.id).all
  end

  def tour_toggle
    current_user.show_tour = false
    if current_user.save
      render :json => { status: "success"}
    else
      render :json => { status: "fail"}
    end
  end

  def pray_for_user
    result = request.location
    @user_action = UserAction.create(:user_id => current_user.id,
      :to_user_id => params[:id],
      :action_type => "prayer_for_user",
      :lat => result.latitude,
      :lng => result.longitude
      )
    if @user_action
      redirect_to "/users"
    end
  end

  def create_prayer_request
    result = request.location
    if result.city.blank?
      result.city << "San Diego"
      result.state << "California"
      result.state_code << "CA"
    end
    @school = SchoolPrayer.where(school_id: params[:school_id]).first

    @user_action = UserAction.create(:school_id => params[:school_id], :user_id => current_user.id,
      :content => params[:content],
      :action_type => "prayer",
      :lat => result.latitude,
      :lng => result.longitude,
      :city => result.city,
      :state => result.state,
      :state_code => result.state_code,
      :postal_code => result.postal_code,
      :country => result.country,
      :country_code => result.country_code,
      :school_name => @school.school_name,
      :school_photo_file_name => @school.photo_file_name
      )
    if @user_action
      render :json => { status: "success", prayer_html:
                                   "<div class=\"row\">
                                        <figure class=\"col-md-1 col-md-offset-1\"><i class=\"fa fa-fire fa-4x text-muted\"></i></figure>
                                        <div class=\"span6\">
                                             <div class=\"comment_name\">Prayer</div>
                                             <div class=\"comment_date\"><i class=\"fa fa-clock-o\"></i> #{@user_action.created_at.strftime("%d %b %Y")}</div>
                                             <div class=\"the_comment\">
                                                  <p>#{@user_action.content}</p>
                                             </div>
                                        </div>
                                   </div>"
      }
    else
      render :json => { status: "fail"}
    end
  end

  def create_school_note
    result = request.location
    @user_action = UserAction.create(:school_id => params[:school_id], :user_id => current_user.id,
      :content => params[:content],
      :action_type => "school_note",
      :lat => result.latitude,
      :lng => result.longitude
      )
    if @user_action
      render :json => { status: "success" }
    else
      render :json => { status: "fail"}
    end
  end

  def map_schools
    if Rails.env.development?
      holder = JSON.parse(open("http://localhost:5000/api/gps_coords?token=784c7d6a5e6af6f24cba13e636ae506e").read)
    else
      holder = SchoolDbGpsSchools.cached_request
    end

    # I had to make my own string to send to the view.  It's a hack I need to fix now that I'm not using gmaps4rails
    @markers = String.new
    @markers = "["
    holder.each do |school|
      @markers += '{"lng" : "%s", "lat" : "%s", "id" : "%s" },' % [school["gps_lng"], school["gps_lat"], school["id"]]
    end
    @markers += '{"lng" : "", "lat" : "", "name" : "", "id" : "" }]'
  end

  def iframe_map
    response.headers.delete "X-Frame-Options"
    response.headers['Content-Security-Policy'] = "child-src 'self' https://*.edify.org http://*.edify.org"
    if Rails.env.development?
      holder = JSON.parse(open("http://localhost:5000/api/gps_coords?token=784c7d6a5e6af6f24cba13e636ae506e").read)
    else
      holder = SchoolDbGpsSchools.cached_request
    end

    # I had to make my own string to send to the view.  It's a hack I need to fix now that I'm not using gmaps4rails
    @markers = String.new
    @markers = "["
    holder.each do |school|
      @markers += '{"lng" : "%s", "lat" : "%s", "id" : "%s" },' % [school["gps_lng"], school["gps_lat"], school["id"]]
    end
    @markers += '{"lng" : "", "lat" : "", "name" : "", "id" : "" }]'
    
    render :layout => false
  end

  def list_schools
    @countries = {1=>"Ghana",2=>"Dominican Republic",3=>"Rwanda",4=>"Burkina Faso",5=>"Liberia",6=>"Peru"}
#     @countries = Hash[country_hash.map {|p| [p.id, p.name]}]
    @schools = SchoolDbAllSchools.cached_request
#     @schools = JSON.parse(open("https://edifydb.herokuapp.com/api/home_data/newest_four?token=#{EdifyDonor::Application.config.school_db_api_token}").read)

  end

  def show_school
    if Rails.env.development?
      @school = JSON.parse(open("http://localhost:5000/api/schools/#{params[:id]}?token=784c7d6a5e6af6f24cba13e636ae506e").read)
      @loan_data = open("http://localhost:5000/api/loans/#{params[:id]}?token=784c7d6a5e6af6f24cba13e636ae506e")
      @enrollment = JSON.parse(open("http://localhost:5000/api/enrollment/#{params[:id]}?token=784c7d6a5e6af6f24cba13e636ae506e").read)
    else
      @school = JSON.parse(open("https://edifydb.herokuapp.com/api/schools/#{params[:id]}?token=#{EdifyDonor::Application.config.school_db_api_token}").read)
      @loan_data = open("https://edifydb.herokuapp.com/api/loans/#{params[:id]}?token=#{EdifyDonor::Application.config.school_db_api_token}")
      @enrollment = JSON.parse(open("https://edifydb.herokuapp.com/api/enrollment/#{params[:id]}?token=#{EdifyDonor::Application.config.school_db_api_token}").read)
    end
    unless @loan_data.read == "null"
      if Rails.env.development?
        @loan = JSON.parse(open("http://localhost:5000/api/loans/#{params[:id]}?token=784c7d6a5e6af6f24cba13e636ae506e").read)
      else
        @loan = JSON.parse(open("https://edifydb.herokuapp.com/api/loans/#{params[:id]}?token=#{EdifyDonor::Application.config.school_db_api_token}").read)
      end
    end

    if @loan.nil?
      @loan_category = "no_loan"
      @loan_use = "Not available"
    else
      @loan_category = @loan["use_of_funds"]
      @loan_use = @loan["use_of_funds_description"]
    end


    @school_prayer = SchoolPrayer.where(:school_id => @school["id"], :user_id => current_user.id)
    @school_visited = SchoolVisit.where(:school_id => @school["id"], :user_id => current_user.id)
    @want_to_visit_school = WantToVisitSchool.where(:school_id => @school["id"], :user_id => current_user.id)

#   http://maps.googleapis.com/maps/api/geocode/json?address=la+romana&sensor=false
    region = CGI.escape(@school['region'])
    geocode_region = JSON.parse(open("http://maps.googleapis.com/maps/api/geocode/json?address=#{region}&sensor=false").read)
    if geocode_region["status"] == "OK"
      @no_coords = geocode_region["results"][0]["geometry"]["location"]["lat"].to_s + "," + geocode_region["results"][0]["geometry"]["location"]["lng"].to_s
      @map_zoom = 7
    else
      @no_coords = "18.735693,-70.162651" # DR
      @map_zoom = 8
    end

  end

  def school_info_window
    @school = JSON.parse(open("https://edifydb.herokuapp.com/api/schools/#{params[:id]}?token=#{EdifyDonor::Application.config.school_db_api_token}").read)

    respond_to do |format|
      format.js
    end
  end

  def iframe_school_info_window
    @school = JSON.parse(open("https://edifydb.herokuapp.com/api/schools/#{params[:id]}?token=#{EdifyDonor::Application.config.school_db_api_token}").read)

    respond_to do |format|
      format.js
    end
  end

  def school_prayer
    puts current_user.id
    @school_prayer = SchoolPrayer.where(:school_id => params[:school_id], :user_id => current_user.id)
    if @school_prayer.blank?
      if Rails.env.development?
        school = JSON.parse(open("http://localhost:5000/api/schools/#{params[:school_id]}?token=784c7d6a5e6af6f24cba13e636ae506e").read)
        enrollment = JSON.parse(open("http://localhost:5000/api/enrollment/#{params[:school_id]}?token=784c7d6a5e6af6f24cba13e636ae506e").read)
      else
        school = JSON.parse(open("https://edifydb.herokuapp.com/api/schools/#{params[:school_id]}?token=#{EdifyDonor::Application.config.school_db_api_token}").read)
        enrollment = JSON.parse(open("https://edifydb.herokuapp.com/api/enrollment/#{params[:school_id]}?token=#{EdifyDonor::Application.config.school_db_api_token}").read)
      end

app/helpers/home_helper.rb
module HomeHelper

  def school_story(random,name,year_founded,environment,proprietor_first,director_first,region,proprietor_gender,enrollment,country)
  
    unknown_start = false
    if year_founded == "1980" or year_founded.blank?
      year_founded = "several years"
      unknown_start = true
    end
    
    case random
    when 0, 1
      @school_story = "You\'ll find #{proprietor_first.titlecase} at #{name.titlecase} in the #{environment} area of the #{region} region in #{country}. "
      if proprietor_gender == "female"
        @school_story += "As the busy proprietress of this school, she works hard to ensure the #{enrollment} students under her care are receiving a "
        @school_story += "high-quality, Christ-centered education."
      else
        @school_story += "As the busy proprietor of this school, he works hard to ensure the #{enrollment} students under his care are receiving a "
        @school_story += "high-quality, Christ-centered education."      
      end
    else
      if unknown_start
        if proprietor_gender == "female"
          @school_story = "For #{year_founded} now, the proprietress of #{name.titlecase}, #{proprietor_first.titlecase}, has worked to create an school where "
          @school_story += "students will come receive a high-quality, Christ-centered education in the #{region} area of #{country}."
        else
          @school_story = "For #{year_founded} now, the proprietor of #{name.titlecase}, #{proprietor_first.titlecase}, has worked to create an school where "
          @school_story += "students will come receive a high-quality, Christ-centered education in the #{region} area of #{country}."
        end
      else
        if proprietor_gender == "female"
          @school_story = "#{name.titlecase} was founded in #{year_founded}. The proprietress of this school, #{proprietor_first.titlecase}, is working hard to create a place where "
          @school_story += "students will come receive a high-quality, Christ-centered education in the #{region} area of #{country}."
        else
          @school_story = "#{name.titlecase} was founded in #{year_founded}. The proprietor of this school, #{proprietor_first.titlecase}, is working hard to create a place where "
          @school_story += "students will come receive a high-quality, Christ-centered education in the #{region} area of #{country}."
        end
      end
    end
  
    return @school_story
  end

  def use_of_funds_icon(use_of_funds)
    case use_of_funds
      when "Construction"
        return content_tag(:i, "", :class => "fa fa-building-o fa-2x fa-fw")
      when "Remodel"
        return content_tag(:i, "", :class => "fa fa-cogs fa-2x fa-fw")
      when "Materials"
        return content_tag(:i, "", :class => "fa fa-book fa-2x fa-fw")
      when "Working Capital"
        return content_tag(:i, "", :class => "fa fa-money fa-2x fa-fw")
      when "Computer Lab"
        return content_tag(:i, "", :class => "fa fa-desktop fa-2x fa-fw")
      else
        return content_tag(:i, "", :class => "fa fa-bolt fa-2x fa-fw")
    end
  end

end

app/views/home/_four_newest_schools.html.erb
<section class="portfolio_strict">
  <div class="container">
    <div class="row isotope_portfolio_container">
      <% photo_id = 1 %>
      <% @newest_four.each do |school| %>
      <% unless school.nil? %>
      <% if photo_id < @newest_four.length %>
      <% profile_photo = get_profile_photo(school["id"]) %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4" id="school_<%=school["id"]%>">
          <div class="portfolio_item">
            <a href="/home/show_schools?id=<%= school["id"] %>" data-path-hover="M 180,190 0,158 0,0 180,0 z">
                <figure style="background-image:url(https://edifydb.s3.amazonaws.com/documents/uploads/<%=profile_photo["id"]-%>/small/<%=profile_photo["upload_file_name"]-%>);">
                 <svg viewBox="0 0 180 320" preserveAspectRatio="none">
                  <path d="M 180,0 0,0 0,0 180,0 z"/>
                 </svg>
                 <figcaption>
                 <% if user_signed_in? %>
                   <p><%= school["name"] %></p>
                   <div class="view_button">View</div>
                 <% else %>
                   <p><%= school["name"] %></p>
                   <div class="view_button">Sign-in to view</div>
                 <% end %>
                 </figcaption>
                </figure>
            </a>
            <div class="portfolio_description">
              <h3><a href="/home/show_schools?id=<%= school["id"] %>"><%= school["name"] %></a></h3>
            </div>
          </div>
        </div>
      <% end %>
      <% end %>
      <% photo_id += 1 %>
      <% end %> <%# newest_four.each %>
    </div>
  </div>
</section>

app/views/home/dashboard.html.erb
<section class="hgroup" id="about_us">
<div class="container">
    <h1>Your Dashboard</h1>
    <h2>This is the place to <strong>see the latest activity</strong> at-a-glance.</h2>
    <ul class="breadcrumb pull-right">
         <li><a href="/">Home</a> </li>
         <li class="active">Dashboard</li>
    </ul>
</div>
</section>
<section class="article-text">
  <div class="container">
    <div class="row">
         <div class="col-md-8">
              <p><strong>Thank you</strong> for your continuing partnership in the work that Edify is doing around the world. You are a vital part
                of our mission to improve and expand low-fee independent Christ-centered schools in Ghana, Rwanda, Burkina Faso, Liberia, Dominican Republic and Peru.
              </p>
              <p class="columns_2"><strong>At Edify, we believe</strong> that education is the greatest opportunity for transformation in the developing
              world.  A young person with expanded knowledge and relevant life skills can create a small business or find employment that will lift his or her
              family out of poverty; a young person grounded in a Christ-centered faith will develop the moral foundation necessary to transform
              a culture and remake a society.  With a dedication to serving the poor, Edify's mission is to increase access to Christ-centered
              education and improve the quality and relevancy of what's taught <strong>in Christ-centered schools.</strong></p>
         </div>
         <div class="col-md-4">
              <blockquote>
                   <% @quote_num = rand(10) %>
                   <p><%= get_quote(@quote_num)[:quote] %></p>
                   <small><cite title="Source Title"><%= get_quote(@quote_num)[:quote_by] %></cite></small>
              </blockquote>
              <div id="prayed_for_you">
                <%#http://jsfiddle.net/nnQYQ/%>
                <% if @recent_prayer_for_donor %>
                  <ul id="notes">
                    <li><div class="tape"></div>
                    <p>We prayed for you today<br/>
                      <span class="text-muted small pull-right"><%= @recent_prayer_for_donor.created_at.strftime("%d %b")%></span>
                    </p></li>
                  </ul>
                <% end %>
              </div>
         </div>
    </div>
    <hr/>
  </div>
</section>
  <section class="call_to_action">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <% if current_user.show_tour %>
          <div id="tourbox" class="tourcontrols">
            <h4>Welcome!</h4>
            <i class="fa fa-flag fa-4x fa-fw"></i>
            <button class="btn btn-large btn-success btn-block" onclick="javascript:introJs().start();">Take a quick tour!</button>
            <a href="javascript:void(0);" onclick="javascript:hideTourBox();">Don't Show This Again</a>
          </div>
          <% end %>
        </div>
        <div class="col-md-4" data-intro="We'd like to introduce you to the schools that are a part of the Edify program." data-step='1'>
            <a href="/home/map_schools"><img src='/images/map.png' width="100" height="100" /></a><br/><h3>Explore</h3>
            <h4 data-intro='Using the School List, you can see all the schools in our program and filter by their region.' data-step='2'><a href="/home/list_schools"><i class="fa fa-group fa-fw"></i> Browse the School List</a></h4>
            <h4 data-intro='Explore the countries in which we work using Google Maps. Most schools are Geo-tagged and you can see exactly where they are in their communities.' data-step='3'><a href="/home/map_schools"><i class="fa fa-map-marker fa-fw"></i> Unfold the School Map</a></h4>
        </div>
        <div class="col-md-4">
            <h4>Recently added schools</h4>
            <%= render "four_newest_stack" %>
        </div>
      </div>
    </div>
  </section>
<section class="call_to_action">
  <div class="container">
    <div class="row text-center">
      <div data-intro='Grow in your knowledge of low-fee independent schools, of international development, and your faith.' data-step='4' class="col-md-3 text-center">
        <i class="fa fa-leaf fa-4x fa-fw"></i><br/>
        <h3>Grow</h3>
        <h4 data-intro='Join in with others in our community and discuss and reflect on a monthly devotional brought to you by various authors.' data-step='5'><a href="/forums"><i class="fa fa-comments-o fa-fw"></i> Devotional</a></h4>
        <h4 data-intro='Dig deeper into our recommended reading lists; discuss and react to the books that inspire and challenge us.' data-step='6'><a href="/forums"><i class="fa fa-book fa-fw"></i> Book Club</a></h4>
      </div>
      <div data-intro='Partner with us financially. Program donations fund loans and training that help improve and expand low-fee Christ-centered education in the countries where we work.' data-step='7' class="col-md-3 text-center">
        <i class="fa fa-money fa-4x fa-fw"></i><br/>
        <h3>Give</h3>
        <h4><a href="/donations/new"><i class="fa fa-credit-card fa-fw"></i>  Make a Donation</a></h4>
        <h4><a href="/fundraisers/new"><i class="fa fa-bullhorn"></i> Start a Fundraiser</a></h4>
      </div>
      <div data-intro='Commit to pray for the schools, their proprietors, teachers, students, parents and their communities.  You can share your prayers publicly for others to join in.' data-step='8'  class="col-md-3 text-center">
        <i class="fa fa-cloud-upload fa-4x fa-fw"></i><br/>
        <h3>God</h3>
        <h4><a href="/home/prayer_list"><i class="fa fa-fire fa-fw"></i> My Prayer List</a></h4>
        <h4><a href="/home/prayer_list"><i class="fa fa-bolt"></i> Global Prayer Feed</a></h4>
      </div>
      <div class="col-md-3 text-center">
        <i class="fa fa-plane fa-4x fa-fw"></i><br/>
        <h3>Go!</h3>
        <h4 data-intro="You can visit our schools any time, virtually.  Take a virtual insight trip through Google Earth and visit the schools we serve." data-step='9' ><a href="/home/virtual_trip"><i class="fa fa-globe fa-fw"></i> Take a Virtual Trip</a></h4>
        <h4 data-intro="If you've had a chance to visit our work first hand, you can create a gallery of the schools you've personally visited." data-step='10' ><a href="/home/schools_visited"><i class="fa fa-map-marker fa-fw"></i> Schools I've Visited</a></h4>
      </div>
    </div>
  </div>
</section>

<% content_for :footer_scripts do %>
<link href="//cdnjs.cloudflare.com/ajax/libs/intro.js/0.5.0/introjs.min.css" rel="stylesheet" type="text/css" />
<link href="/stylesheets/tourtip.css" rel="stylesheet" type="text/css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/intro.js/0.5.0/intro.min.js" type="text/javascript"></script>
<script type="text/javascript">
function hideTourBox(e) {
  $("#tourbox").remove();
  $.post("/home/tour_toggle",{},"json").done();
};
</script>
<% end %>

<% if @recent_prayer_for_donor %>
<% content_for :jit_header do %>
<link href='http://fonts.googleapis.com/css?family=Reenie+Beanie&subset=latin' rel='stylesheet' type='text/css'>
<style type="text/css">
#notes li {
    position: relative;
    width: 300px;
    min-height: 75px;
    margin: 25px auto;
    padding: 15px;
    background: #f1f3a2;
    background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgba(247,247,210,1)), to(rgba(240,242,155,1)));
    background: -moz-linear-gradient(top, rgba(247,247,210,1), rgba(240,242,155,1));
    -webkit-box-shadow: 0 2px 12px rgba(0,0,0,.5);
    -moz-box-shadow: 0 2px 12px (rgba(0,0,0.5));
    box-shadow: 0 1px 2px #000;
    -webkit-transform: rotate(-.5deg);
    -moz-transform: rotate(-.5deg);
    -o-transform: rotate(-.5deg);
}

#notes li:nth-child(even) {
    -webkit-transform: rotate(.5deg);
    -moz-transform: rotate(.5deg);
    -o-transform: rotate(.5deg);
}

#notes li p {
    text-align: center;
    font: normal normal normal 28px/32px 'Reenie Beanie', Helvetica, Arial, sans-serif;
    color: #000;
    text-shadow: white 1px 1px 0px;
    overflow:hidden;
}

#notes li div.tape {
    position: absolute;
    left: 115px;
    top: -15px;
    width: 75px;
    height: 25px;
    z-index: 2;
    background-color: rgba(243,245,228,0.5);
    border: 2px solid rgba(255,255,255,0.5);
    -webkit-transform: rotate(-6deg);
    -moz-transform: rotate(-6deg);
    -o-transform: rotate(-6deg);
}

#notes li:nth-child(even) div.tape {
    -webkit-transform: rotate(6deg);
    -moz-transform: rotate(6deg);
    -o-transform: rotate(6deg);
}
</style>
<% end %>
<% end %>

app/views/home/index.html.erb
<% content_for :four_newest_schools do %>

<%= render "four_newest_schools" %>

<% end %>

app/views/home/my_fundraisers.html.erb
<section class="hgroup" id="portfolio">
<div class="container">
    <h1>My Fundraisers</h1>
    <h2><strong>Engage</strong> your friends and family in the work of Edify!</h2>
    <ul class="breadcrumb pull-right">
         <li><a href="/">Home</a> </li>
         <li>My Portfolio </li>
         <li class="active">My Fundraisers</li>
    </ul>
</div>
</section>
<section class="article-text">
  <div class="container">


<table class="table table-bordered table-striped">
  <tr>
    <th>Name</th>
    <th>Shareable Link</th>
    <th>Goal Amount</th>
    <th>End date</th>
    <th></th>
    <th></th>
  </tr>

<% @fundraisers.each do |fundraiser| %>
  <tr>
    <td><%= fundraiser.name %></td>
    <td><%= fundraiser.friendly_url %></td>
    <td><%= number_to_currency((fundraiser.goal_amount_cents / 100), precision: 0) %></td>
    <td><%= fundraiser.end_date.strftime("%d-%b-%Y") %></td>
    <td><%= link_to 'Show', fundraiser %></td>
    <td><%= link_to 'Edit', edit_fundraiser_path(fundraiser) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Start A New Fundraiser', new_fundraiser_path, class: 'btn btn-default' %>

  </div>
</section>