config/routes.rb
EdifyDonor::Application.routes.draw do

  resources :categories, :except => [:index, :show]
#   resources :forums, :except => :index do
#     resources :topics, :shallow => true, :except => :index do
#       resources :posts, :shallow => true, :except => [:index, :show]
#     end
#     root to: 'categories#index', via: :get
#   end

  authenticated :user do
#     root :to => 'home#dashboard'
    get 'home/list_schools', to: 'home#list_schools'
    get 'schools', to: 'home#list_schools'
    get 'home/show_schools', to: 'home#show_school'
    get 'home/show_schools/:id', to: 'home#show_school'
    get 'school/:id', to: 'home#show_school'
    get 'home/map_schools', to: 'home#map_schools'
    get 'map', to: 'home#map_schools'
    get 'home/dashboard', to: 'home#dashboard'
    get 'home/prayer_list', to: 'home#prayer_list'
    get 'home/prayer_feed', to: 'home#prayer_feed'
    get 'home/school_prayer', to: 'home#school_prayer'
    get 'home/school_visited', to: 'home#school_visited'
    get 'home/want_to_visit_school', to: 'home#want_to_visit_school'
    get 'home/school_visit_tour', to: 'home#school_visit_tour'
    get 'home/virtual_trip', to: 'home#virtual_trip'
    get 'home/tour', to: 'home#tour'
    get 'home/create_prayer_request', to: 'home#create_prayer_request'
    get 'home/pray_for_user/:id', to: 'home#pray_for_user'
    get 'home/create_school_note', to: 'home#create_school_note'
    get 'home/impact_portfolio', to: 'home#impact_portfolio'
    get 'home/schools_visited', to: 'home#schools_visited'
    get 'home/recently_added', to: 'home#recently_added'
    get 'home/tour_toggle', to: 'home#tour_toggle'
    get 'home/my_fundraisers', to: 'home#my_fundraisers'

    # get 'fundraisers/new', to: 'fundraisers#new'
    # get 'fundraisers/edit', to: 'fundraisers#edit'


    get 'home/school_info_window/:id', to: 'home#school_info_window'

#     if Rails.env.production?
# #       scope :protocol => 'http://', :constraints => { :protocol => 'http://', :domain => "edify-donor.herokuapp.com" } do
# #         resources :donations, :constraints => { :protocol => 'http://', :domain => "edify-donor.herokuapp.com" }
# #       end
#       get 'donations/new', to: redirect("http://edify-donor.herokuapp.com/donations/new"), :constraints => { :protocol => "http://" }
#     end
    get 'donations/fundraiser', to: 'donations#fundraiser'
    get 'donations/create_fundraiser_donation', to: 'donations#create_fundraiser_donation'

    resources :donations
    get 'fundraisers/list', to: 'fundraisers#list'

    resources :fundraisers
  end
  
  get 'iframe_map', to: 'home#iframe_map'
  get 'iframe_school_info_window/:id', to: 'home#iframe_school_info_window'
  
  get 'fundraisers/list', to: 'fundraisers#list'
  get 'fundraisers', to: 'fundraisers#index'
  get 'fundraisers/:id', to: 'fundraisers#show'
  get 'donations/fundraiser', to: 'donations#fundraiser'
  get 'donations/create_fundraiser_donation', to: 'donations#create_fundraiser_donation'

  root :to => "home#index"
  devise_for :users
  resources :users


end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :user
  attr_accessible :total_amount, :amount_cents, :billing_address, :billing_city, :billing_state, :billing_zip
  attr_accessible :transaction_id, :transaction_result, :user_id, :amount_cents
  attr_accessible :billing_first, :billing_last, :card_brand, :card_expires_on
  attr_accessible :card_number, :card_verification
  attr_accessor :card_number, :card_verification

  has_many :transactions, :class_name => "DonationTransaction"
  belongs_to :fundraiser

  validate :validate_card, :on => :create

  def donate
    response = GATEWAY.purchase(donation_in_cents, credit_card, purchase_options)
    transactions.create!(:action => "purchase", :amount => donation_in_cents, :response => response)
    self.update_attribute(:donated_at, Time.now) if response.success?
    response.success?
  end

  def donation_in_cents
    amount_cents
  end

  private

  def purchase_options
    {
      :ip => ip_address,
      :billing_address => {
        :name     => billing_first+billing_last,
        :address1 => billing_address,
        :city     => billing_city,
        :state    => billing_state,
        :country  => "US",
        :zip      => billing_zip
      }
    }
  end

  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        errors.add :base, "message"
      end
    end
  end

  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      :brand              => card_brand,
      :number             => card_number,
      :verification_value => card_verification,
      :month              => card_expires_on.month,
      :year               => card_expires_on.year,
      :first_name         => billing_first,
      :last_name          => billing_last
    )
  end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
require 'pp'
require 'rubygems'
require 'active_merchant'
require 'json'
  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  def fundraiser
    @donation = Donation.new
    @fundraiser = Fundraiser.where(id: params[:fundraiser_id].to_i).first
    @gift_amount = params[:gift_amount]
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create    
  @donation = Donation.new(params[:donation])
  @donation.amount_cents = (params[:donation][:total_amount].to_f * 100)
  @donation.ip_address = request.remote_ip
  @donation.user_id = current_user.id

    respond_to do |format|
      if @donation.save
          if @donation.donate
            format.html do
              @transaction = DonationTransaction.where(donation_id: @donation.id)
              @ctr = @transaction.first.params["ctr"].sub("Purchase", "Donation")
              UserMailer.donation_receipt(current_user,@donation,@ctr).deliver
              UserMailer.donation_staff_notification(current_user,@donation,@ctr).deliver
              render action: "thanks", notice: 'Donation was successful.'
            end
            format.json { render json: @donation, status: :created, location: @donation }
          else
            render :action => "try_again", notice: 'Donation was not successful.'
          end
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /donations
  # POST /donations.json
  def create_fundraiser_donation    
  @donation = Donation.new(params[:donation])
  @donation.amount_cents = (params[:donation][:total_amount].to_f * 100)
  @donation.ip_address = request.remote_ip
  @donation.user_id = current_user.id unless current_user.blank?
  @donation.fundraiser_id = params[:fundraiser_id]

    respond_to do |format|
      if @donation.save
          if @donation.donate
            format.html do
              @transaction = DonationTransaction.where(donation_id: @donation.id)
              @ctr = @transaction.first.params["ctr"].sub("Purchase", "Donation")
              UserMailer.donation_receipt(current_user,@donation,@ctr).deliver
              UserMailer.donation_staff_notification(current_user,@donation,@ctr).deliver
              render action: "thanks", notice: 'Donation was successful.'
            end
            format.json { render json: @donation, status: :created, location: @donation }
          else
            render :action => "try_again", notice: 'Donation was not successful.'
          end
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  def thanks
    
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/donations_helper.rb
module DonationsHelper

  def get_us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

end

app/views/donations/_form.html.erb
<%= simple_form_for(@donation) do |f| %>
  <%= f.error_notification %>
      <div class="pane" style="display:block">
        <input name="item_description" id="item_description" type="hidden" value="General Donation via myEdify" />
        <label>Amount:</label>
        <div class="input-group col-md-4">
          <span class="input-group-addon">$</span>
          <%= f.text_field :total_amount, :required => true, :class=>'form-control' %>
          <span class="input-group-addon">.00</span>
        </div>
        <div class="clr"></div>
      </div>
<div class="row">
<div class="col-md-6">
                	<!-- BILLING BLOCK -->
                <h2>Billing Information</h2>
                <div>
                 	<label>Name:</label>
                    <%= f.text_field :billing_first, :class=>"col-md-2 form-control", :placeholder => "First name", :required => true %>&nbsp;<%= f.text_field :billing_last, :class=>"col-md-2 form-control", :placeholder => "Last name", :required => true %>
                    <div class="clr"></div>
                    
                     <label>Address:</label>
                    <%= f.text_field :billing_address, :class=>"col-md-5 form-control", :required => true %>
                    <div class="clr"></div>
                    
                     <label>City:</label>
                    <%= f.text_field :billing_city, :class=>"col-md-3 form-control", :required => true %>
                    <div class="clr"></div>
                       <label>State & ZIP</label>
                    <%= f.select :billing_state, options_for_select(get_us_states), :class=>'form-control' %>&nbsp;<%= f.text_field :billing_zip, :class=>"small-field form-control", :required => true %>
                    <div class="clr"></div>
                </div>
                <!-- BILLING BLOCK -->
</div>
<div class="col-md-6">   
                <!-- CREDIT CARD BLOCK -->
                <h2>Credit Card Information</h2>
                <div>
                    <div class="clr"></div>
                    <div class="ccinfo">
                    <label>Card Number:</label>
                    <div class="input-group">
                      <span class="input-group-addon" id="cc-types">
                        <i class="fa fa-cc-visa"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-amex"></i>
                        <i class="fa fa-cc-discover"></i>
                      </span>
                      <%= f.text_field :card_number, :class=>"long-field form-control", :maxlength=>"16", :required => true, :placeholder=>"Credit Card Number" %>

                    </div>
                    <div class="clr"></div>
                    
                    <label>Expiration Date:</label>
                      <%= f.date_select :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true, :class=>'form-control' %>
                    <div class="clr"></div>
                    <label>CVV:<i class="fa fa-question-sign"></i></a></label>
                    <%= f.text_field :card_verification, :required => true, :class=>"form-control col-md-1" %>
                      <div class="clr"></div>
                      <br/><br/>
                      <%= f.button :submit, :class=>"btn btn-success col-md-5", :value => "Donate", :id => "donate_button" %>
              
                  </div>    
                </div>
            	<!-- CREDIT CARD BLOCK -->
</div></div>
            	<% end %>
            	
<% content_for :jit_header do %>
<script type="text/javascript" src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<script type="text/javascript" src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.min.js"></script>
<script type="text/javascript" src="/js/autoNumeric.js"></script>
<% end %>

<script type="text/javascript">
jQuery(function($) {
  $('#donation_total_amount').autoNumeric('init',{vMax: '999999.99'});    
});

$(function(){
  //custom validator for money fields
  $.validator.addMethod("money", function (value, element) {
     return this.optional(element) || value.match(/^\d+(.(\d{2}))?/);
  }, "Please provide a valid dollar amount (up to 2 decimal places)<br/><strong>DO NOT</strong> include a dollar ($) sign.");

  $("#new_donation").validate({
    rules: {
      "donation[total_amount]": {
        required: true,
        money: true },
      "donation[billing_first]": "required",
      "donation[billing_last]": "required",
      "donation[billing_address]": "required",
      "donation[billing_city]": "required",
      "donation[billing_zip]": {
        required: true,
        zipcodeUS: true },
      "donation[card_number]": "required",
      "donation[card_verification]": "required"
    },
    errorClass: "text-error",
    validClass: "text-success",
    submitHandler: function(form) {
      $("#donate_button").prop("disabled",true);
            var v = $('#donation_total_amount').autoNumeric('get');
            $('#donation_total_amount').autoNumeric('destroy');
            $('#donation_total_amount').val(v);
      form.submit();
    }    
  });
});
</script>

app/views/donations/_fundraiser_form.html.erb
<%= form_for @donation, url: { action: "create_fundraiser_donation" } do |f| %>
  
      <div class="pane" style="display:block">
        <input name="item_description" id="item_description" type="hidden" value="Donation via myEdify Fundraiser" />
        <input name="fundraiser_id" id="fundraiser_id" type="hidden" value="<%=@fundraiser.id%>" />
<% if params[:gift_amount].blank? %>
        <label>Please Choose Gift Amount:</label>
        <div class="input-group col-md-4">
          <span class="input-group-addon">$</span>
          <%= f.text_field :total_amount, :required => true, :class=>'form-control' %>
          <span class="input-group-addon">.00</span>
        </div>
        <div class="clr"></div>
<% else %> 
        <label>Amount:</label>
        <div class="input-group col-md-4">
          <span class="input-group-addon">$</span>
          <%= f.text_field :total_amount, :required => true, :class=>'form-control', :value => @gift_amount %>
          <span class="input-group-addon">.00</span>
        </div>
        <div class="clr"></div>
<% end %>
      </div>
<div class="row">
<div class="col-md-6">
                	<!-- BILLING BLOCK -->
                <h2>Billing Information</h2>
                <div>
                 	<label>Name:</label>
                    <%= f.text_field :billing_first, :class=>"col-md-2 form-control", :placeholder => "First name", :required => true %>&nbsp;<%= f.text_field :billing_last, :class=>"col-md-2 form-control", :placeholder => "Last name", :required => true %>
                    <div class="clr"></div>
                    
                     <label>Address:</label>
                    <%= f.text_field :billing_address, :class=>"col-md-5 form-control", :required => true %>
                    <div class="clr"></div>
                    
                     <label>City:</label>
                    <%= f.text_field :billing_city, :class=>"col-md-3 form-control", :required => true %>
                    <div class="clr"></div>
                       <label>State & ZIP</label>
                    <%= f.select :billing_state, options_for_select(get_us_states), :class=>'form-control' %>&nbsp;<%= f.text_field :billing_zip, :class=>"small-field form-control", :required => true %>
                    <div class="clr"></div>
                </div>
                <!-- BILLING BLOCK -->
</div>
<div class="col-md-6">   
                <!-- CREDIT CARD BLOCK -->
                <h2>Credit Card Information</h2>
                <div>
                    <div class="clr"></div>
                    <div class="ccinfo">
                    <label>Card Number:</label>
                    <div class="input-group">
                      <span class="input-group-addon" id="cc-types">
                        <i class="fa fa-cc-visa"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-amex"></i>
                        <i class="fa fa-cc-discover"></i>
                      </span>
                      <%= f.text_field :card_number, :class=>"long-field form-control", :maxlength=>"16", :required => true, :placeholder=>"Credit Card Number" %>

                    </div>
                    <div class="clr"></div>
                    
                    <label>Expiration Date:</label>
                      <%= f.date_select :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true, :class=>'form-control' %>
                    <div class="clr"></div>
                    <label>CVV:<i class="fa fa-question-sign"></i></a></label>
                    <%= f.text_field :card_verification, :required => true, :class=>"form-control col-md-1" %>
                      <div class="clr"></div>
                      <br/><br/>
                      <%= f.button :submit, :class=>"btn btn-success col-md-5", :value => "Donate", :id => "donate_button" %>
              
                  </div>    
                </div>
            	<!-- CREDIT CARD BLOCK -->
</div></div>
            	<% end %>
            	
<% content_for :jit_header do %>
<script type="text/javascript" src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<script type="text/javascript" src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.min.js"></script>
<script type="text/javascript" src="/js/autoNumeric.js"></script>
<% end %>

<script type="text/javascript">
jQuery(function($) {
  $('#donation_total_amount').autoNumeric('init',{vMax: '999999.99'});    
});

$(function(){
  //custom validator for money fields
  $.validator.addMethod("money", function (value, element) {
     return this.optional(element) || value.match(/^\d+(.(\d{2}))?/);
  }, "Please provide a valid dollar amount (up to 2 decimal places)<br/><strong>DO NOT</strong> include a dollar ($) sign.");

  $("#new_donation").validate({
    rules: {
      "donation[total_amount]": {
        required: true,
        money: true },
      "donation[billing_first]": "required",
      "donation[billing_last]": "required",
      "donation[billing_address]": "required",
      "donation[billing_city]": "required",
      "donation[billing_zip]": {
        required: true,
        zipcodeUS: true },
      "donation[card_number]": "required",
      "donation[card_verification]": "required"
    },
    errorClass: "text-error",
    validClass: "text-success",
    submitHandler: function(form) {
      $("#donate_button").prop("disabled",true);
            var v = $('#donation_total_amount').autoNumeric('get');
            $('#donation_total_amount').autoNumeric('destroy');
            $('#donation_total_amount').val(v);
      form.submit();
    }    
  });
});
</script>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/fundraiser.html.erb
<% if @fundraiser.blank? %>
  <a href="/fundraisers">Please choose a fundraiser to support.</a>
<% else %>
<% if GATEWAY.test? %>
<div class="container">
  <div class="row">
    <br/>
    <div class="alert alert-danger">
      <h4 class="alert-heading">WARNING: DONATION FORM IN TEST MODE</h4>
      <p>The donation form is set to test mode, entering a real credit card number will not be processed.<br/>
      Use Test Card: 4111111111111111 :: 01/<%=(Date.today + 1.year).strftime("%Y")%> :: CVV 123</p>
    </div>
  </div>
</div>
<% end %>
<section class="hgroup" id="portfolio">
<div class="container">
      <h1>Contribute to <%=@fundraiser.name %> Fundraiser</h1>
      <h2>Thank you for joining with <%=@fundraiser.user.name %></h2>
    <ul class="breadcrumb pull-right">
         <li><a href="/">Home</a> </li>
         <li class="active">Donate</li>
    </ul>
</div>
</section>
<section class="article-text">
  <div class="container">

    <h3>Donation Information</h3> 
    <%= render 'fundraiser_form' %>

</div>
</section>
<% end %>

app/views/donations/index.html.erb
<section class="hgroup" id="about_us">
<div class="container">
    <h1>Donations</h1>
    <ul class="breadcrumb pull-right">
         <li><a href="/">Home</a> </li>
         <li class="active">Users</li>
    </ul>
</div>
</section>
<section class="article-text">
  <div class="container">
    <div class="row">
         <div class="col-md-12">

          <table class="table table-striped table-bordered">
            <tr>
              <th>User</th>
              <th>Amount in cents</th>
              <th>Billing address</th>
              <th>Billing city</th>
              <th>Billing state</th>
              <th>Billing zip</th>
              <th colspan="3">Actions</th>
            </tr>
          
          <% @donations.each do |donation| %>
            <tr>
              <td><%= donation.user.name %></td>
              <td><%= donation.amount_cents %></td>
              <td><%= donation.billing_address %></td>
              <td><%= donation.billing_city %></td>
              <td><%= donation.billing_state %></td>
              <td><%= donation.billing_zip %></td>
              <td><%= link_to 'Show', donation %></td>
              <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
              <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
          </table>

         </div>
    </div>
  </div>
</section>

app/views/donations/new.html.erb
<% if GATEWAY.test? %>
<div class="container">
  <div class="row">
    <br/>
    <div class="alert alert-danger">
      <h4 class="alert-heading">WARNING: DONATION FORM IN TEST MODE</h4>
      <p>The donation form is set to test mode, entering a real credit card number will not be processed.<br/>
      Use Test Card: 4111111111111111 :: 01/<%=(Date.today + 1.year).strftime("%Y")%> :: CVV 123</p>
    </div>
  </div>
</div>
<% end %>
<section class="hgroup" id="portfolio">
<div class="container">
    <h1>Make a donation</h1>
    <h2>Further the <strong>work</strong> of Edify through your financial <strong>generosity.</strong></h2>
    <ul class="breadcrumb pull-right">
         <li><a href="/">Home</a> </li>
         <li class="active">Donate</li>
    </ul>
</div>
</section>
<section class="article-text">
  <div class="container">

    <h3>Donation Information</h3> 
<%= render 'form' %>

</div>
</section>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @donation.user_id %>
</p>

<p>
  <b>Amount in cents:</b>
  <%= @donation.amount_cents %>
</p>

<p>
  <b>Billing address:</b>
  <%= @donation.billing_address %>
</p>

<p>
  <b>Billing city:</b>
  <%= @donation.billing_city %>
</p>

<p>
  <b>Billing state:</b>
  <%= @donation.billing_state %>
</p>

<p>
  <b>Billing zip:</b>
  <%= @donation.billing_zip %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/donations/thanks.html.erb
<section class="hgroup" id="portfolio">
<div class="container">
    <h1>Thank you for your donation</h1>
    <h2>You are helping to further the <strong>work</strong> of Edify through your financial <strong>generosity.</strong></h2>
    <ul class="breadcrumb pull-right">
         <li><a href="/">Home</a> </li>
         <li><a href="/donate/new">Donate</a> </li>
         <li class="active">Thanks!</li>
    </ul>
</div>
</section>
<section class="article-text">
  <div class="container">

<div class="alert alert-success">
Credit card approved.
</div>
      <p>Thank you for your generous donation in support of the work of Edify.</p>
      
      <p>Your donation will help expand our programs in sustainable, affordable Christian schools in Ghana, Rwanda, 
      Burkina Faso, Liberia and the Dominican Republic.</p>
      
      <p>Kind Regards,</p>
      
      <p>The Edify Team</p>
      
      <strong>A receipt has been sent to your registered email address.</strong>
      
      <%= simple_format(@transaction.first.params["ctr"].sub("Purchase", "Donation")) %>
      
      <p><em>Edify is a 501(c)3 nonprofit organization, Federal Tax ID# 27-0892545<br/>
      No goods or services were received in consideration of this gift.</em></p>
      
      <p>Edify - 10590 W. Ocean Air Dr.,Ste 300 - San Diego, CA 92130 - toll free: 855-GO-EDIFY</p>

</article>
</section>

app/views/donations/try_again.html.erb
Failed. Try again.