config/routes.rb
EdifyDonor::Application.routes.draw do

  resources :categories, :except => [:index, :show]
#   resources :forums, :except => :index do
#     resources :topics, :shallow => true, :except => :index do
#       resources :posts, :shallow => true, :except => [:index, :show]
#     end
#     root to: 'categories#index', via: :get
#   end

  authenticated :user do
#     root :to => 'home#dashboard'
    get 'home/list_schools', to: 'home#list_schools'
    get 'schools', to: 'home#list_schools'
    get 'home/show_schools', to: 'home#show_school'
    get 'home/show_schools/:id', to: 'home#show_school'
    get 'school/:id', to: 'home#show_school'
    get 'home/map_schools', to: 'home#map_schools'
    get 'map', to: 'home#map_schools'
    get 'home/dashboard', to: 'home#dashboard'
    get 'home/prayer_list', to: 'home#prayer_list'
    get 'home/prayer_feed', to: 'home#prayer_feed'
    get 'home/school_prayer', to: 'home#school_prayer'
    get 'home/school_visited', to: 'home#school_visited'
    get 'home/want_to_visit_school', to: 'home#want_to_visit_school'
    get 'home/school_visit_tour', to: 'home#school_visit_tour'
    get 'home/virtual_trip', to: 'home#virtual_trip'
    get 'home/tour', to: 'home#tour'
    get 'home/create_prayer_request', to: 'home#create_prayer_request'
    get 'home/pray_for_user/:id', to: 'home#pray_for_user'
    get 'home/create_school_note', to: 'home#create_school_note'
    get 'home/impact_portfolio', to: 'home#impact_portfolio'
    get 'home/schools_visited', to: 'home#schools_visited'
    get 'home/recently_added', to: 'home#recently_added'
    get 'home/tour_toggle', to: 'home#tour_toggle'
    get 'home/my_fundraisers', to: 'home#my_fundraisers'

    # get 'fundraisers/new', to: 'fundraisers#new'
    # get 'fundraisers/edit', to: 'fundraisers#edit'


    get 'home/school_info_window/:id', to: 'home#school_info_window'

#     if Rails.env.production?
# #       scope :protocol => 'http://', :constraints => { :protocol => 'http://', :domain => "edify-donor.herokuapp.com" } do
# #         resources :donations, :constraints => { :protocol => 'http://', :domain => "edify-donor.herokuapp.com" }
# #       end
#       get 'donations/new', to: redirect("http://edify-donor.herokuapp.com/donations/new"), :constraints => { :protocol => "http://" }
#     end
    get 'donations/fundraiser', to: 'donations#fundraiser'
    get 'donations/create_fundraiser_donation', to: 'donations#create_fundraiser_donation'

    resources :donations
    get 'fundraisers/list', to: 'fundraisers#list'

    resources :fundraisers
  end
  
  get 'iframe_map', to: 'home#iframe_map'
  get 'iframe_school_info_window/:id', to: 'home#iframe_school_info_window'
  
  get 'fundraisers/list', to: 'fundraisers#list'
  get 'fundraisers', to: 'fundraisers#index'
  get 'fundraisers/:id', to: 'fundraisers#show'
  get 'donations/fundraiser', to: 'donations#fundraiser'
  get 'donations/create_fundraiser_donation', to: 'donations#create_fundraiser_donation'

  root :to => "home#index"
  devise_for :users
  resources :users


end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Associations
  has_many :forums, :dependent => :destroy
  
  # Accessors
  attr_accessible :title, :state, :position, :category_id
  
  # Scopes
  default_scope {order('position ASC')}
  
  # Validations
  validates :title,       :presence => true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController  
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(params[:category])
    
    if @category.save
      flash[:notice] = "Category was successfully created."
      redirect_to forums_url
    else
      render :action => 'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    
    if @category.update_attributes(params[:category])
      flash[:notice] = "Category was updated successfully."
      redirect_to forums_url
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    
    if @category.destroy
      flash[:notice] = "Category was deleted."
      redirect_to forums_url
    end
  end
end

app/views/categories/_form.html.erb
<div class="module">
  <div class="module_header"><%= action_name.humanize %> Category</div>
    <div class="module_subheader smaller"></div>
    <div class="module_body">
      <%= form_for @category do |f| %>
      <% if @category.errors.any? %>
        <% flash.now[:error] = @category.errors.full_messages.join(', and ') %>
      <% end %>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :title %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_field :title, :size => 75 %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :position %>
        </span>
        <span class="input indent smaller"><%= f.text_field :position %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller"></span>
        <span class="input indent smaller">
          <%= f.check_box :state %>
          <%= f.label :state %>
        </span>
        <div class="clear"></div>
      </div>
    </div>
    <div class="module_footer">
      <div class="fieldset">
        <span class="input"><%= f.submit "submit" %> or <%= link_to "cancel", forums_path %></span>
        <div class="clear"></div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<section id="portfolio">
<div class="hgroup">
    <h1>Discussions</h1>
    <h2><strong>Grow</strong> in your knowledge. <strong>Connect</strong> with others.</h2>
    <ul class="breadcrumb pull-right">
         <li><a href="/">Home</a> <span class="divider">/</span></li>
         <li class="active">Discussions</li>
    </ul>
</div>
<article>
<div class="right controls"><% if current_user.has_role? :admin %><%= link_to "New Forum Category", new_category_path %><% end %></div>
<% @categories.each do |category| %>
  <div class="module">
    <div class="module_header">
      <%= category.title %>
      <span class="controls right smaller">
        <% if current_user.has_role? :admin %>
        <%= link_to "New Forum", new_forum_path %>
        <%= link_to "Edit Category", edit_category_path(category) %>
        <%= link_to "Delete Category", category_path(category), :confirm => "Are you sure you want to delete this category?", :method => :delete %>
        <% end %>
      </span>
    </div>
    <% if category.forums.size > 0 %>
    <div>
      <table>
        <tr class="smaller">
          <th colspan="2" align="left">Forum</th>
          <th>Topics</th>
          <th>Posts</th>
          <th class="last_post" align="left">Last Post</th>
        </tr>
        <% category.forums.each do |forum| %>
        <tr>
          <td class="icon"><i class="fa fa-comments-o fa-2x"></i></td>
          <td class="description">
            <%= link_to forum.title, forum_path(forum) %><br />
            <span class="smaller"><%= forum.description %></span><br />
          </td>
          <td class="counts smaller"><%= forum.topics.size %></td>
          <td class="counts smaller"><%= forum.posts.size - forum.topics.size %></td>
          <td class="last_post smaller">
            <% if forum.posts.size > 0 %>
              <%= forum.posts.last.created_at %><br />
              <%= forum.posts.last.user.username %>
            <% else %>
              No Topics / Posts
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <% else %>
      <div class="module_body">There are currently no forums.</div>
    <% end %>
  </div>
<% end %>
</article>
</section>

app/views/categories/new.html.erb
<%= render :partial => 'form' %>