config/routes.rb
EdifyDonor::Application.routes.draw do

  resources :categories, :except => [:index, :show]
#   resources :forums, :except => :index do
#     resources :topics, :shallow => true, :except => :index do
#       resources :posts, :shallow => true, :except => [:index, :show]
#     end
#     root to: 'categories#index', via: :get
#   end

  authenticated :user do
#     root :to => 'home#dashboard'
    get 'home/list_schools', to: 'home#list_schools'
    get 'schools', to: 'home#list_schools'
    get 'home/show_schools', to: 'home#show_school'
    get 'home/show_schools/:id', to: 'home#show_school'
    get 'school/:id', to: 'home#show_school'
    get 'home/map_schools', to: 'home#map_schools'
    get 'map', to: 'home#map_schools'
    get 'home/dashboard', to: 'home#dashboard'
    get 'home/prayer_list', to: 'home#prayer_list'
    get 'home/prayer_feed', to: 'home#prayer_feed'
    get 'home/school_prayer', to: 'home#school_prayer'
    get 'home/school_visited', to: 'home#school_visited'
    get 'home/want_to_visit_school', to: 'home#want_to_visit_school'
    get 'home/school_visit_tour', to: 'home#school_visit_tour'
    get 'home/virtual_trip', to: 'home#virtual_trip'
    get 'home/tour', to: 'home#tour'
    get 'home/create_prayer_request', to: 'home#create_prayer_request'
    get 'home/pray_for_user/:id', to: 'home#pray_for_user'
    get 'home/create_school_note', to: 'home#create_school_note'
    get 'home/impact_portfolio', to: 'home#impact_portfolio'
    get 'home/schools_visited', to: 'home#schools_visited'
    get 'home/recently_added', to: 'home#recently_added'
    get 'home/tour_toggle', to: 'home#tour_toggle'
    get 'home/my_fundraisers', to: 'home#my_fundraisers'

    # get 'fundraisers/new', to: 'fundraisers#new'
    # get 'fundraisers/edit', to: 'fundraisers#edit'


    get 'home/school_info_window/:id', to: 'home#school_info_window'

#     if Rails.env.production?
# #       scope :protocol => 'http://', :constraints => { :protocol => 'http://', :domain => "edify-donor.herokuapp.com" } do
# #         resources :donations, :constraints => { :protocol => 'http://', :domain => "edify-donor.herokuapp.com" }
# #       end
#       get 'donations/new', to: redirect("http://edify-donor.herokuapp.com/donations/new"), :constraints => { :protocol => "http://" }
#     end
    get 'donations/fundraiser', to: 'donations#fundraiser'
    get 'donations/create_fundraiser_donation', to: 'donations#create_fundraiser_donation'

    resources :donations
    get 'fundraisers/list', to: 'fundraisers#list'

    resources :fundraisers
  end
  
  get 'iframe_map', to: 'home#iframe_map'
  get 'iframe_school_info_window/:id', to: 'home#iframe_school_info_window'
  
  get 'fundraisers/list', to: 'fundraisers#list'
  get 'fundraisers', to: 'fundraisers#index'
  get 'fundraisers/:id', to: 'fundraisers#show'
  get 'donations/fundraiser', to: 'donations#fundraiser'
  get 'donations/create_fundraiser_donation', to: 'donations#create_fundraiser_donation'

  root :to => "home#index"
  devise_for :users
  resources :users


end

app/views/layouts/_footer.html.erb
<footer>
  <section class="twitter_feed_wrapper">
       <div class="container">
            <div class="row wow animated fadeInUp">
                 <div class="twitter_feed_icon col-sm-1 col-md-1"><a href="#"><i class="fa fa-comments"></i></a></div>
                 <div class="col-sm-11 col-md-11">
                      <blockquote>
                        <% footer_quote = rand(10); if footer_quote == @quote_num then footer_quote += 1 end-%>
                          <p><%= get_quote(footer_quote)[:quote] %></p>
                          &mdash; <%= get_quote(footer_quote)[:quote_by] %></blockquote>
                 </div>
            </div>
       </div>
  </section>
  <section id="footer_teasers_wrapper">
       <div class="container">
            <div class="row">
                 <div class="footer_teaser col-sm-4 col-md-4">
                      <h3>Our Mission:</h3>
                      <p>To improve and to expand low-fee, Christ-centered education in the developing world.</p>
                      <p><i class="fa fa-map-marker"></i> 10590 W Ocean Air Dr., Ste. 300, San Diego, CA 92130</p>
                      <p><i class="fa fa-phone"></i> Toll Free: 855-GO-EDIFY</p>
                      <p><i class="fa fa-envelope"></i> info@edify.org</p>
                 </div>
                 <div class="footer_teaser col-sm-4 col-md-4">
                      <h3>Latest News</h3>
                      <ul class="media-list">
                           <li class="media"> <a href="#" class="media-photo" style="background-image:url(/assets/edify_logo_greybg_64x64.png)"></a> <a href="#" class="media-date"><%= Date.today.strftime("%e") %><span><%= Date.today.strftime("%^b") %></span></a>
                                <h5 class="media-heading"><a href="#">Edify launches an exclusive new site!</a></h5>
                                <p>The private beta for {my}edify has been launched to help connect our supporters to our work...</p>
                           </li>
                      </ul>
                 </div>
                 <div class="col-md-4 footer_teaser" id="">
                      <h3>Real-Time Prayer Feed</h3>
                      <% prayer_feed = UserAction.where(action_type: "prayer").order("created_at DESC").limit(2).all %>
                      <% prayer_feed.each do |prayer| %>
                      <% prayer.school_photo_file_name.blank? ? school_photo = "/assets/edify_logo_greybg_64x64.png" : school_photo = "http://s3.amazonaws.com/edifydb/thumb/#{prayer.school_id}/#{prayer.school_photo_file_name}" %>
                      <ul class="media-list">
                           <li class="media"> <a href="/home/show_schools/<%=prayer.school_id%>" class="media-photo" style="background-image:url(<%=school_photo%>)"></a> <a href="/home/show_schools/<%=prayer.school_id%>" class="media-date">JOIN<span>IN</span></a>
                                <h5 class="media-heading"><a href="/home/show_schools/<%=prayer.school_id%>"><%=prayer.school_name%></a></h5>
                                <p>Someone in <%=prayer.city%>, <%=prayer.state_code%> prayed for this school.</p>
                           </li>
                      </ul>
                      <% end %>
                 </div>
            </div>
       </div>
  </section>
  <section class="copyright">
     <div class="container">
          <div class="row">
               <div class="col-md-6"> Copyright &copy;<%= Date.today.strftime("%Y")%> all rights reserved.  Edify is a registered 501(c)3 Non-Profit Organization </div>
               <div class="col-md-6 text-right"></div>
          </div>
     </div>
  </section>
</footer>

app/views/layouts/_header.html.erb
<!doctype html>
<html class="no-js" lang="en">
<head>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,600italic,700,700italic,300italic" rel="stylesheet" type="text/css">
<meta charset="utf-8">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="/animate.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="/js/woothemes-FlexSlider-06b12f8/flexslider.css" type="text/css" media="screen">
<link rel="stylesheet" href="/js/prettyPhoto_3.1.5/prettyPhoto.css" type="text/css" media="screen">
<link href="/style.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<script type="text/javascript" src="/js/modernizr.custom.48287.js"></script>
    <title><%= content_for?(:title) ? yield(:title) : "{my}edify" %></title>
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Edify Donor" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= jquery_include_tag :google %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  <%= yield :jit_header %>
</head>

<body class="<%= controller_name %> <%= action_name %> collapsing_header">

<header>
  <div class="container">
    <div class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <a class="navbar-brand" href="/"><%#image_tag "edify_logo_black.png", height: 51, width:153%><span class="logo_title">{my} edify </span>
        <span class="logo_subtitle">A deeper engagement with Edify</span> </a><a class="btn btn-navbar btn-default navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="nb_left pull-left"> <span class="fa fa-reorder"></span></span> <span class="nb_right pull-right">menu</span> </a>
      </div>
      <div class="collapse navbar-collapse">
      
            <%= render 'layouts/navigation' %>
      
      </div>
    </div>
    <% if user_signed_in? %>
      <div id="sign">
        <a href="#"><i class="fa fa-user"></i><span> Logged in as <%= current_user.name %></a>
        <%= link_to '<i class="fa fa-cog"></i>'.html_safe, edit_user_registration_path %> | 
        <%= link_to '<i class="fa fa-sign-out"></i>'.html_safe, destroy_user_session_path, :method=>'delete' %></span>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <br/>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %> alert-dismissable">
            <a class="close" data-dismiss="alert"><i class="fa fa-cross"></i></a>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <ul class="nav pull-right navbar-nav">
    <li><a href="/home/dashboard"><i class="fa fa-home"></i></a></li>
    <li class="dropdown"><a href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-book"></i> My Portfolio <b class="caret"></b></a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
        <li role="presentation"><a href="/home/prayer_list"><i class="fa fa-fw fa-fire"></i> My Prayer List</a></li>
        <li role="presentation"><a href="/home/schools_visited"><i class="fa fa-fw fa-map-marker"></i> Schools I've Visited</a></li>
        <li role="presentation"><a href="/home/virtual_trip"><i class="fa fa-fw fa-globe"></i> Virtual Trip Itinerary</a></li>
        <li role="presentation"><a href="/home/my_fundraisers"><i class="fa fa-fw fa-bullhorn"></i> My Fundraisers</a></li>
        <li role="presentation"><a href="/home/impact_portfolio"><i class="fa fa-fw fa-dashboard"></i> My Impact Portfolio</a></li>
      </ul>
    </li>
    <li class="dropdown"><a href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-compass"></i> Explore <b class="caret"></b></a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
        <li role="presentation"><a href="/home/list_schools"><i class="fa fa-group fa-fw"></i> All Schools</a></li>
        <li role="presentation"><a href="/home/map_schools"><i class="fa fa-map-marker fa-fw"></i> Map View</a></li>
        <li role="presentation"><a href="/home/recently_added"><i class="fa fa-certificate fa-fw"></i> Recently Added</a></li>
        <li role="presentation"><a href="/home/prayer_feed"><i class="fa fa-bolt fa-fw"></i> Global Prayer Feed</a></li>
      </ul>
    </li>
    <li><a href="/forums"><i class="fa fa-comments-o"></i> Discuss and Grow</a></li>
    <li><a href="/donations/new"><i class="fa fa-credit-card"></i> Donate</a></li>
    <% if current_user.has_role? :admin %>
    <li id="fat-menu" class="dropdown">
      <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-wrench"></i> <b class="caret"></b></a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
        <li role="presentation"><%= link_to 'User Admin', users_path, :role=>"menuitem", :tabindex=>"-1" %></li>
        <li role="presentation"><%= link_to 'Donations', donations_path, :role=>"menuitem", :tabindex=>"-1" %></li>
    </ul>
    </li>
    <% end %>
  </ul>

<% else %>
<ul class="nav pull-right navbar-nav">
  <li><%= link_to 'Sign in', new_user_session_path %></li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>

<div class="main">
  <%= render 'layouts/messages' %>
  <%= yield %>

  <%= render 'layouts/footer' %>

</div> <!-- div#main -->

<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="/js/woothemes-FlexSlider-06b12f8/jquery.flexslider-min.js"></script>
<script src="/js/prettyPhoto_3.1.5/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
<script src="/js/isotope/jquery.isotope.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/jquery.ui.totop.js"></script>
<script type="text/javascript" src="/js/easing.js"></script>
<script type="text/javascript" src="/js/wow.min.js"></script>
<script type="text/javascript" src="/js/snap.svg-min.js"></script>
<script type="text/javascript" src="/js/restart_theme.js"></script>
<script type="text/javascript" src="/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="/js/z.jquery.fileupload.js"></script>
<%= yield :scripts %>
<%= yield :footer_scripts %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-18352775-4', 'myedify.org');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/layouts/index.html.erb
<%= render 'layouts/header' %>

<section id="slider_wrapper" class="slider_wrapper container">
     <div id="main_flexslider" class="flexslider">
          <ul class="slides">
               <li class="item"  style="background-image: url(https://www.edify.org/wp-content/uploads/2012/12/2012.12.gh_.jpeg)">
                    <div class="container">
                         <div class="carousel-caption">
                              <h1>a <strong>new</strong> way you can be<br>
                                   involved in the work of <strong>Edify</strong></h1>
                              <p class="lead inverse">{my}edify is built to serve you.  Dig deeper into our work.</p>
                    </div>
               </li>
               <li class="item"  style="background-image: url(https://www.edify.org/wp-content/uploads/2012/12/2012.12.dr2_.jpeg)">
                    <div class="container">
                         <div class="carousel-caption">
                              <h1><strong>prayer</strong> makes a difference<br>
                                   here and <strong>around the world</strong>!</h1>
                              <p class="lead inverse">Join us in prayer for the schools we serve.</p>
                         </div>
                    </div>
               </li>
               <li class="item"  style="background-image: url(https://www.edify.org/wp-content/uploads/2013/08/map.jpg)">
                    <div class="container">
                         <div class="carousel-caption">
                              <h1 class="inverse"><strong>real</strong> schools<br>
                                   in real <strong>communities</strong></h1>
                              <p class="lead">Edify partner schools bring the love of Jesus Christ to their communities every day.</p>
                         </div>
                    </div>
               </li>
          </ul>
     </div>
</section>
<div id="main">
     <div class="container">
          <section class="call_to_action">
               <h3>focus on what's important</h3>
               <h4>and connect with Edify's work around the world</h4>
                 <% if !user_signed_in? %>
                   <%= link_to 'Sign in', new_user_session_path, :class=>"btn btn-primary btn-large" %>
                 <% end %>  
          <section id="features_teasers_wrapper">
               <div class="row">
                    
                    <div class="col-md-4 feature_teaser"> <i style="color:#039d23" class="fa fa-4x fa-fw fa-dashboard"></i><br/><br/>
                         <h3>Your Impact Portfolio</h3>
                         <p>Your donation goes to help fund loans and training for schools.  Learn more about the schools that have been impacted through your support.</p>
                    </div>
                    <div class="col-md-4 feature_teaser"> <i style="color:#157fb2" class="fa fa-4x fa-fw fa-globe inverse"></i><br/><br/>
                         <h3>Schools You've Visited</h3>
                         <p>Had the chance to visit our work personally?  Keep track of the schools you have personally visited. Haven't visited our work yet? Take a virtual trip!</p>
                    </div>
                    <div class="col-md-4 feature_teaser"> <i style="color:#d85006" class="fa fa-4x fa-fw fa-fire"></i><br/><br/>
                         <h3>Join us in Prayer</h3>
                         <p>Make a prayer list of the Edify Partner Schools and share your prayers publicly so that they may be encouraged and others can join in!</p>
                    </div>
               </div>   
          </section>


          <%= yield(:four_newest_schools) %>
          

     </div>
     
    <%= render 'layouts/footer' %>
</div> <!-- div#main -->

<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script>window.jQuery || document.write('<script src="/js/jquery-1.9.0.min.js"><\/script>')</script>
<script src="/twitter-bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/js/woothemes-FlexSlider-06b12f8/jquery.flexslider-min.js"></script>
<script src="/js/prettyPhoto_3.1.5/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
<script src="/js/isotope/jquery.isotope.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/jquery.ui.totop.js"></script>
<script type="text/javascript" src="/js/easing.js"></script>
<script type="text/javascript" src="/js/wow.min.js"></script>
<script type="text/javascript" src="/js/snap.svg-min.js"></script>
<script type="text/javascript" src="/js/restart_theme.js"></script>
<%= yield :scripts %>
<%= yield :footer_scripts %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-18352775-4', 'myedify.org');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/layouts/map.html.erb
<%= render 'layouts/header' %>
<section id="above_map" class="container">
  <%= render 'layouts/messages' %>
  <%= yield(:above_map) %>
</section>
  <%= yield %>
<div id="main" role="main">
  <div class="container">
    <div class="content">
       <div class="row">
        <div class="col-md-12">
          <%= yield(:below_map) %>
        </div>
      </div>
    </div>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
<%= render 'layouts/footer' %>